name: Build image

on: 
  push:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch:
          - [aarch64-linux-gnn, aarch64, /opt/externs/libs]
          - [arm-linux-gnueabihf, armv4, /opt/externs/libs]
          - [arm-linux-gnueabi, armv7, /opt/externs/libs]
          - [x86_64-linux-gnu, x86_64, /usr/local]

    steps:
      - uses: actions/checkout@v2
