name: Build old image

on: 
  push:
  release:
    types:
      - published

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch:
          - [aarch64-linux-gnn, aarch64, /opt/externs/libs]
          - [arm-linux-gnueabihf, armv4, /opt/externs/libs]
          - [x86_64-linux-gnu, x86_64, /usr/local]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/.docker-buildx-cache
          key: docker-buildx
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/neuron/${{ matrix.arch[1] }}
      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=local,src=/tmp/.docker-buildx-cache,mode=max
          cache-to: type=local,dest=/tmp/.docker-buildx-cache-new,mode=max
          platforms: linux/amd64
          tags: neugates/build_old:${{ matrix.arch[1] }}-2.2
          file: .github/old_dockerfile/${{ matrix.arch[1] }}_Dockerfile
          context: .
      - name: Update cache
        run: |
          rm -rf /tmp/.docker-buildx-cache
          mv /tmp/.docker-buildx-cache-new /tmp/.docker-buildx-cache



      

